version: '3'
services:
  moviesapi:
    build: MoviesAPI/
    ports:
      - "8082:80"
      - "8083:443"
   
  seriesapi:
    build: SeriesAPI/
    ports:
      - "8084:80"
      - "8085:443"
    

  envoygateway:
    build: Envoy/
    ports:
      - "9901:9901"
      - "10000:10000"
      - "10001:10001"
    volumes:
      - ./Envoy/envoy.yaml:/etc/envoy/envoy.yaml
 